---
version: "2.1"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Sydney
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorent/config:/config
      - <path/to/your/download-folder>:/downloads
    
    # Traefik network, comment if not using
    networks:
      - proxy
    ports:
      - target: 6881
        published: 6881
        protocol: tcp
      - target: 6881
        published: 6881
        protocol: udp
    # Uncomment if not using Traefik
    #ports:
    #  - 8080:8080
    #  - 6881:6881
    #  - 6881:6881/udp
    restart: unless-stopped
    # Traefik Labels and network, comment if not using
    labels:
                        - "traefik.enable=true"
                        - "traefik.http.routers.qbittorrent.entrypoints=http"
                        - "traefik.http.routers.qbittorrent.rule=Host(`example.yourdomain.com`)"
                        - "traefik.http.middlewares.qbittorrent-https-redirect.redirectscheme.scheme=https"
                        - "traefik.http.routers.qbittorrent.middlewares=qbittorrent-https-redirect"
                        - "traefik.http.routers.qbittorrent-secure.entrypoints=https"
                        - "traefik.http.routers.qbittorrent-secure.rule=Host(`example.yourdomain.com`)"
                        - "traefik.http.routers.qbittorrent-secure.tls=true"
                        - "traefik.http.routers.qbittorrent-secure.service=qbittorrent"
                        - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
                        - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
...
