---
version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Sydney
    # Traefik network, comment if Traefik not configured  
    networks:
      - proxy
    volumes:
      - ./heimdall/config:/config
    #ports:
    #  - 8500:80
    #  - 4430:443
    restart: unless-stopped
    # Traefik Labels and Network, comment if useless
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.entrypoints=http"
      - "traefik.http.routers.heimdall.rule=Host(`example.yourdomain.com`)"
      - "traefik.http.middlewares.heimdall-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.heimdall.middlewares=heimdall-https-redirect"
      - "traefik.http.routers.heimdall-secure.entrypoints=https"
      - "traefik.http.routers.heimdall-secure.rule=Host(`example.yourdomain.com`)"
      - "traefik.http.routers.heimdall-secure.tls=true"
      - "traefik.http.routers.heimdall-secure.service=heimdall"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      # Uncomment if you have authelia configured
      #- "traefik.http.routers.heimdall-secure.middlewares=authelia@docker"
networks:
  proxy:
    external: true

