version: '3'

services:
  file:
    image: filebrowser/filebrowser
    container_name: file
    user: 1000:1000
    volumes:
      - /:/srv # path to the root of your server
      - ./filebrowser/filebrowser.db:/database.db
    # Traefik network comment if you don't have it configured
    networks:
      - proxy
    # Uncomment if Traefik not configured
    #ports:
    #  - 8080:80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # Traefik labels and network comment if you don't have it configured
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file.entrypoints=http"
      - "traefik.http.routers.file.rule=Host(`file.doriath931.xyz`)"
      - "traefik.http.middlewares.file-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.file.middlewares=file-https-redirect"
      - "traefik.http.routers.file-secure.entrypoints=https"
      - "traefik.http.routers.file-secure.rule=Host(`file.doriath931.xyz`)"
      - "traefik.http.routers.file-secure.tls=true"
      - "traefik.http.routers.file-secure.service=file"
      - "traefik.http.services.file.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    # Uncomment if you have authelia configured
    #  - "traefik.http.routers.ombi-secure.middlewares=authelia@docker"
networks:
  proxy:
    external: true
