---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0 # put in `id -u` and `id -g` of the user your want to use
      - PGID=0
      - TZ=Pacific/Sydney
    #  - CLI_ARGS= #optional
    volumes:
      - ./duplicati/config:/config
      - <path/to/your/backup-folder>:/backups
      - <path/to/your/source-folder>:/source
    ports:
      - 8200:8200
    restart: unless-stopped