---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Sydney
      - AUTO_UPDATE=true #optional
    volumes:
      - ./config:/config
      - </path/to/your/data>:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
networks:
  proxy:
    external: true