---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Sydney
    volumes:
      - ./config:/config
      - <path/to/your/data>:/data
    ports:
      - 8989:8989
    restart: unless-stopped
networks:
  proxy:
    external: true